### ISSUE TITLE
About FLOPs 

### ISSUE THREAD

**Issue by longmalongma** [Zhang-VISLab/Learning-to-Segment-3D-Point-Clouds-in-2D-Image-Space#12]
Thanks for your great work, what's the FLOPs of your segmentation model on the Shapenet Part? looking forward to your reply.

**Comment by YechengLyu** [comment]
The FLOPs is 33.8G calculated by the [keras_flops](https://pypi.org/project/keras-flops/).

Yecheng

**Comment by longmalongma** [comment]
> The FLOPs is 33.8G calculated by the [keras_flops](https://pypi.org/project/keras-flops/).
> 
> Yecheng

Thanks for your reply. what's the FLOPs of your segmentation model on the s3dis dataset?

**Comment by YechengLyu** [comment]
It is 33.1G accordingly. It is different from the Shapenet model only because it maps to 13 semantic categories instead of 50 in the last network layer.

**Comment by longmalongma** [comment]
> 因此是33.1G。它与Shapenet模型的不同之处仅在于它映射到13个语义类别，而不是最后一个网络层的50个语义类别。

Thanks. What are the predicted results of miou and OA of your network on the S3DIS data set? If you can give the data, I will quote your paper and conduct comparative experiments

**Comment by Zhang-VISLab** [comment]
Dear longmalongma,

We have not fully tested our method on S3DIS dataset. Stay tuned for our update.
