### ISSUE TITLE
How to convert a stack of images into a point cloud?

### ISSUE THREAD

**Issue by monjoybme** [Zhang-VISLab/Learning-to-Segment-3D-Point-Clouds-in-2D-Image-Space#17]
I am curious to know if you have any code for the conversion of a stack of images into 3d point clouds. To use your code I first need to convert images into point clouds.

**Comment by YechengLyu** [comment]
The code you mentioned is included in S3_network_testing.py  Line 53-86.

Yecheng

**Comment by monjoybme** [comment]
@YechengLyu Thanks for your comments. Based on line 68 I think we need a trained model for this. But I want to use my own .PNG image data. Hence, do you have any code for converting PNGs to Point Cloud?

**Comment by YechengLyu** [comment]
There is no way to convert "PNG" image data to point cloud without the 3D-to-2D mapping. Please see function GPGL2_seg in S1_network_dataset_preparation.py how to generate the 3D-to-2D mapping.

**Comment by Zhang-VISLab** [comment]
Hi monjoybme,

Is your problem solved? Thanks.

**Comment by monjoybme** [comment]
Hi, Thanks for your suggestion. It helped me a lot. I am closing this issue.
