### ISSUE TITLE
grid size

### ISSUE THREAD

**Issue by ghost** [Zhang-VISLab/Learning-to-Segment-3D-Point-Clouds-in-2D-Image-Space#6]
@YechengLyu Hello. I try to project 16384 points to a 256×256 grid, but an error arised in 'fun_GPGL_layout_push()' function:

'pos_target  = pos_empty[np.argmin(dist)]'
'ValueError: attempt to get argmin of an empty sequence.'

Is it caused by the SIZE_SUB and SIZE_TOP parameters? By the way, do you have any advice for the grid size and K to reduce the point collision rate for 16384 points?

**Comment by YechengLyu** [comment]
@GoCrazySSS This error happens when the you have an cluster of points exceeds the pre-defined patch size 16x16. To avoid that you can increase the SIZE_SUB to 20 or 24. Usually I set the NUM_CUTS to the squared root of the point size.

**Comment by ghost** [comment]
I solved this by setting SIZE_TOP and SIZE_SUB as 24, and thank you so much for your suggestions！------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Yecheng&amp;nbsp;Lyu&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月9日(星期四) 晚上10:37
收件人:&nbsp;&quot;Zhang-VISLab/Learning-to-Segment-3D-Point-Clouds-in-2D-Image-Space&quot;<Learning-to-Segment-3D-Point-Clouds-in-2D-Image-Space@noreply.github.com&gt;;
抄送:&nbsp;&quot;Yufei Sun&quot;<1289989665@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Zhang-VISLab/Learning-to-Segment-3D-Point-Clouds-in-2D-Image-Space] grid size (#6)
