### ISSUE TITLE
Missing implementation

### ISSUE THREAD

**Issue by hi-zhengcheng** [Zhang-VISLab/Learning-to-Segment-3D-Point-Clouds-in-2D-Image-Space#9]
https://github.com/Zhang-VISLab/Learning-to-Segment-3D-Point-Clouds-in-2D-Image-Space/blob/d5a914d9012fc993480733bcdc87218f2ed0e046/data_preparation_testing.py#L127

@Zhang-VISLab It seems that the implementation of function `loadDataFile_with_seg` is missing in `provider.py`. Maybe some code is not committed yet.

**Comment by YechengLyu** [comment]
Thanks for letting me know, I have added them back to provider.py.
